name: sum_thing
description: Sums up all the QR-bills amounts.
version: 1.0.1
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
